name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: macos-12
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.5.0
        with:
          java-version: ${{ matrix.java }}
          distribution: microsoft
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Barrel
          path: target/Barrel-1.0.0-SNAPSHOT.jar
